


 
let keycodes = {
    8: "BackSpace BackSpace",
    9: "Tab Tab",
    12: "Clear",
    13: "Enter",
    16: "Shift_L",
    17: "Control_L",
    18: "Alt_L",
    19: "Pause",
    20: "Caps_Lock",
    27: "Escape Escape",
    32: "space space",
    33: "Prior",
    34: "Next",
    35: "End",
    36: "Home",
    37: "Left",
    38: "Up",
    39: "Right",
    40: "Down",
    41: "Select",
    42: "Print",
    43: "Execute",
    45: "Insert",
    46: "Delete",
    47: "Help",
    48: "0 equal braceright",
    49: "1 exclam onesuperior",
    50: "2 quotedbl twosuperior",
    51: "3 section threesuperior",
    52: "4 dollar",
    53: "5 percent",
    54: "6 ampersand",
    55: "7 slash braceleft",
    56: "8 parenleft bracketleft",
    57: "9 parenright bracketright",
    65: "a A",
    66: "b B",
    67: "c C",
    68: "d D",
    69: "e E EuroSign",
    70: "f F",
    71: "g G",
    72: "h H",
    73: "i I",
    74: "j J",
    75: "k K",
    76: "l L",
    77: "m M mu",
    78: "n N",
    79: "o O",
    80: "p P",
    81: "q Q at",
    82: "r R",
    83: "s S",
    84: "t T",
    85: "u U",
    86: "v V",
    87: "w W",
    88: "x X",
    89: "y Y",
    90: "z Z",
    96: "KP_0 KP_0",
    97: "KP_1 KP_1",
    98: "KP_2 KP_2",
    99: "KP_3 KP_3",
    100: "KP_4 KP_4",
    101: "KP_5 KP_5",
    102: "KP_6 KP_6",
    103: "KP_7 KP_7",
    104: "KP_8 KP_8",
    105: "KP_9 KP_9",
    106: "KP_Multiply KP_Multiply",
    107: "KP_Add KP_Add",
    108: "KP_Separator KP_Separator",
    109: "KP_Subtract KP_Subtract",
    110: "KP_Decimal KP_Decimal",
    111: "KP_Divide KP_Divide",
    112: "F1",
    113: "F2",
    114: "F3",
    115: "F4",
    116: "F5",
    117: "F6",
    118: "F7",
    119: "F8",
    120: "F9",
    121: "F10",
    122: "F11",
    123: "F12",
    124: "F13",
    125: "F14",
    126: "F15",
    127: "F16",
    128: "F17",
    129: "F18",
    130: "F19",
    131: "F20",
    132: "F21",
    133: "F22",
    134: "F23",
    135: "F24",
    136: "Num_Lock",
    137: "Scroll_Lock",
    187: "acute grave",
    188: "comma semicolon",
    189: "minus underscore",
    190: "period colon",
    192: "numbersign apostrophe",
    210: "plusminus hyphen macron",
    211: "",
    212: "copyright registered",
    213: "guillemotleft guillemotright",
    214: "masculine ordfeminine",
    215: "ae AE",
    216: "cent yen",
    217: "questiondown exclamdown",
    218: "onequarter onehalf threequarters",
    220: "less greater bar",
    221: "plus asterisk asciitilde",
    227: "multiply division",
    228: "acircumflex Acircumflex",
    229: "ecircumflex Ecircumflex",
    230: "icircumflex Icircumflex",
    231: "ocircumflex Ocircumflex",
    232: "ucircumflex Ucircumflex",
    233: "ntilde Ntilde",
    234: "yacute Yacute",
    235: "oslash Ooblique",
    236: "aring Aring",
    237: "ccedilla Ccedilla",
    238: "thorn THORN",
    239: "eth ETH",
    240: "diaeresis cedilla currency",
    241: "agrave Agrave atilde Atilde",
    242: "egrave Egrave",
    243: "igrave Igrave",
    244: "ograve Ograve otilde Otilde",
    245: "ugrave Ugrave",
    246: "adiaeresis Adiaeresis",
    247: "ediaeresis Ediaeresis",
    248: "idiaeresis Idiaeresis",
    249: "odiaeresis Odiaeresis",
    250: "udiaeresis Udiaeresis",
    251: "ssharp question backslash",
    252: "asciicircum degree",
    253: "3 sterling",
    254: "Mode_switch"
}





let cssExample ="html {\n    font-size: 12px !important;\n    background: url(\"\") !important;\n    top: 0;\n    left: 0;\n    background-color: rgba(0, 0, 0, 0.753) !important;\n    background-attachment: fixed !important;\n    background-size: contain !important;\n    -webkit-background-size: contain !important;\n    -o-background-size: contain !important;\n    -moz-background-size: contain !important;\n    background-repeat: repeat !important;\n    background-position: center !important;\n     \n    zoom: 1;\n    /* scrollbar */\n    /* scrollbar-width: none; firefox */\n    overflow: auto;\n    \n}\n/* scrollbar */\n::-webkit-scrollbar {\n    /* display: none; */\n    width: 12px; \n    background: transparent !important;\n}\n/* -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0) !important; */\n::-webkit-scrollbar-track {  \n    -webkit-box-shadow:none  !important;\n    border-radius: 10px;\n    background : transparent !important;\n}\n::-webkit-scrollbar-track-piece{\n    -webkit-box-shadow:none  !important;\n    background : transparent !important;\n}\n::-webkit-scrollbar-thumb {\n    border-radius: 10px;\n    background: rgba(7, 250, 250, 0.5);\n    -webkit-box-shadow:none  !important;\n}\n::-webkit-scrollbar-thumb:window-inactive {\n    background: rgba(123, 83, 235, 0.6)!important;\n}\n\nbody {\n    background-color: transparent !important;\n    background: transparent !important; \n}\n\ndiv {\n    line-height: 25px !important;\n    background-image: none !important;\n    background-color: transparent !important;\n    background: transparent !important;\n}\n\np,\nspan {\n    line-height: 25px !important;\n    text-indent: 38px !important;\n}\n\nul,\nli,\n[id*=recommend-],\n[class*=recommend-] {\n    background-image: none !important;\n    background-color: transparent !important;\n    background: transparent !important;\n}\n\n/*****************************↓↓↓↓ for special site ↓↓↓↓*****************************************/\n\nmain .htmledit_views p,\nmain .markdown_views p,\nmain .htmledit_views h1,\nmain .markdown_views h1,\n.content h5 {\n    color: #000 !important;\n}\n\n.nodata .recommend-right #recommend-right .recommend-fixed-box li.right-item .content h5 {\n    color: #000 !important;\n}\n\naside #asideProfile .data-info .count {\n    color: #000 !important;\n}\n\naside div.aside-box .aside-content a {\n    color: #000 !important;\n}\n\nmain .recommend-box .recommend-item-box .title-box .tit {\n    color: #000 !important;\n}\nmain div.blog-content-box .article-header-box h1.title-article {\n    color: #000 !important;\n}\nmain div.blog-content-box .article-header-box .artic-tag-box a.tag-link {\n    color: #000 !important;\n    background-color: transparent !important;\n    background: transparent !important;\n}\nmain .comment-box .comment-content {\n    background-color: transparent !important;\n    background: transparent !important;\n}\n\n.nodata .recommend-right #recommend-right .recommend-fixed-box {\n    background-color: transparent !important;\n    background: transparent !important;\n}\n\nmain .recommend-box .recommend-item-box {\n    background-color: transparent !important;\n    background: transparent !important;\n}\n\nmain ul li {\n    background-color: transparent !important;\n    background: transparent !important;\n}\n\n/***************************↑↑↑↑ for special site ↑↑↑↑*****************************************/\n\n* {\n    text-shadow: 0 0 1px #fff,\n        0 0 4px #fff,\n        0 0 6px #fff,\n        0 0 5px #ff2d95,\n        0 0 4px #ff2d95,\n        0 0 2px #ff2d95,\n        0 0 4px #ff2d95,\n        0 0 3px #ff2d95 !important;\n\n    color: #000 !important;\n    letter-spacing: 2px !important;\n    box-shadow: none !important;\n    font-weight: bold !important;\n    background-color: transparent !important;\n    /* border-color: #444 !important; */\n    border-color: transparent !important;\n    border-top-color: transparent !important;\n    border-bottom-color: transparent !important;\n    border-left-color: transparent !important;\n    border-right-color: transparent !important;\n\n    /**         Examples Of Text Color         \n                 -------------------------------------------------         \n                 color: rgba(0, 0, 0, 1) !important;         \n                 text-shadow: 2px 2px 9px rgba(255, 255, 255, 1) !important;         \n                 -------------------------------------------------         \n                 text-shadow: 0 0 0 3px white, 0 0 2px 6px magenta, 0 0 1px 9px white, 0 0 6px 12px magenta;         \n                 color: magenta !important;         \n                 -------------------------------------------------         \n                 text-shadow: magenta 0px 2px,         \n                     magenta 2px 0px,         \n                     magenta -2px 0px,         \n                     magenta 0px -2px,         \n                     magenta -1.4px -1.4px,         \n                     magenta 1.4px 1.4px,         \n                     magenta 1.4px -1.4px,         \n                     magenta -1.4px 1.4px !important;         \n                 -------------------------------------------------         \n                 text-shadow: magenta 0px 0.3px,         \n                     magenta 0.3px 0px,         \n                     magenta -0.3px 0px,         \n                     magenta 0px -0.3px,         \n                     magenta -0.3px -0.3px,         \n                     magenta 0.3px 0.3px,         \n                     magenta 0.3px -0.3px,         \n                     magenta -0.3px 0.3px !important;         \n                      \n                 -------------------------------------------------         \n                  lower            \n                      \n                 color: #000;         \n                 text-shadow: 0 0 1px #fff,         \n                     0 0 2px #fff,         \n                     0 0 3px #fff,         \n                     0 0 4px #ff2d95,         \n                     0 0 5px #ff2d95,         \n                     0 0 6px #ff2d95,         \n                     0 0 7px #ff2d95,         \n                     0 0 8px #ff2d95 !important;         \n                 letter-spacing: 1px;         \n                      \n                 -------------------------------------------------         \n                      \n                  better-03          \n                      \n                 text-shadow: 0 0 1px #fff,         \n                     0 0 4px #fff,         \n                     0 0 6px #fff,         \n                     0 0 5px #ff2d95,         \n                     0 0 4px #ff2d95,         \n                     0 0 2px #ff2d95,         \n                     0 0 4px #ff2d95,         \n                     0 0 3px #ff2d95 !important;         \n                      \n                 -------------------------------------------------         \n                      \n                  good-03         \n                      \n                 text-shadow: 0 0 1px #fff,         \n                     0 0 1px #fff,         \n                     0 0 2px #fff,         \n                     0 0 2px #ff2d95,         \n                     0 0 3px #ff2d95,         \n                     0 0 3px #ff2d95,         \n                     0 0 4px #ff2d95,         \n                     0 0 4px #ff2d95 !important;         \n                 -------------------------------------------------         \n                      \n                  Burning Text Effect:          \n                      \n                 color: #fff;         \n                 text-shadow: 0px -1px 4px white, 0px -2px 10px yellow, 0px -10px 20px #ff8000, 0px -18px 40px red;         \n                      \n                 -------------------------------------------------         \n                 */\n\n}\n\n \n*:before,\n*:after {\n    background-color: transparent !important;\n    border-color: #444 !important;\n}\n\na,\na * {\n    background-color: transparent !important;\n    color: #8B0000 !important;\n    text-decoration: none !important;\n}\n\na:hover,\na:hover *,\na:visited:hover,\na:visited:hover *,\nspan[onclick]:hover,\ndiv[onclick]:hover,\n[role=\"  link\"]:hover,\n[role=\"  link\"]:hover *,\n[role=\"  button\"]:hover *,\n[role=\"  menuitem\"]:hover,\n[role=\"  menuitem\"]:hover *,\n.link:hover,\n.link:hover * {\n    /* color: #F0F0F0 !important; */\n    text-shadow: 0 0 3px rgba(255, 255, 200, 0) !important;\n    background-color: transparent !important;\n}\n\na:visited,\na:visited * {\n    color: #3700ff !important;\n    text-shadow: 0 0 1px #000000,\n        0 0 4px #000000,\n        0 0 6px #000000,\n        0 0 5px #000000,\n        0 0 4px #000000,\n        0 0 2px #000000,\n        0 0 4px #000000,\n        0 0 3px #000000 !important;\n    background-color: transparent !important;\n}\n\na.highlight,\na.highlight *,\na.active,\na.active *,\n.selected,\n.selected *,\n[href=\"  #\"] {\n    /* color: #DDD !important; */\n    color: #000 !important;\n    font-weight: bold !important;\n    background-color: transparent !important;\n}\n\nh1,\nh2,\nh3,\nh4,\nh5,\nh6,\nh1 *,\nh2 *,\nh3 *,\nstrong,\n[id*=\"  headline\"],\n[class*=\"  headline\"],\n[id*=\"  header\"],\n[class*=\"  header\"],\n[class*=\"  header\"] td {\n    /* color: #000 !important; TTT */\n    background-color: transparent !important;\n}\n\na h1,\na h2,\na h3,\na h4,\na h5,\na h6,\nh1 a,\nh2 a,\nh3 a,\na strong,\na[id*=\"  headline\"],\na[class*=\"  headline\"],\na[id*=\"  header\"],\na[class*=\"  header\"] {\n    text-decoration: underline !important;\n    background-color: transparent !important;\n}\n\n[class*=\"  error\"],\n[class*=\"  alert\"],\ncode,\nspan[onclick],\ndiv[onclick] {\n    color: #900 !important;\n    background-color: transparent !important;\n}\n\n::-moz-selection {\n    /* background-color: transparent !important;  */\n    background: rgb(102, 0, 102) !important;\n\n    color: rgb(130, 255, 255) !important;\n}\n\n::selection {\n    /*  background-color: transparent !important;  */\n    background: rgb(102, 0, 102) !important;\n\n    color: rgb(130, 255, 255) !important;\n}\n\n:focus {\n    outline: none !important;\n}\n\n/*----- MENU & CO BACKGROUND-COLORS -----*/\ndiv[style=\"  display: block;\"],\ndiv[role=\"  navigation\"] {\n\n    background: rgba(0, 0, 0, .3) !important;\n    background-color: transparent !important;\n}\n\n\n\ntable {\n    background: rgba(40, 30, 30, 0) !important;\n    border-radius: 6px !important;\n}\n\ntable>tbody>tr:nth-child(even),\ntable>tbody>tr>td:nth-child(even) {\n    background-color: rgba(0, 0, 0, 0) !important;\n}\n\niframe,\nembed,\nnav,\nlabel [onclick],\nnav ul,\ndiv[style*=\"  position:\"][style*=\"  left:\"][style*=\"  visible\"],\ndiv[style*=\"  z-index:\"][style*=\"  left:\"][style*=\"  visible\"],\ndiv[style*=\"  -moz-user-select\"],\ndiv[role=\"  menu\"],\ndiv[role=\"  dialog\"],\nspan[class*=\"  script\"] div,\n[id*=\"  menu\"],\n[id*=\"  Menu\"],\n[class*=\"  dropdown\"],\n[class*=\"  popup\"],\n[class=\"  title\"],\nul[style*=\"  display:\"],\nul[style*=\"  visibility:\"] ul,\n[id*=\"  nav\"] ul,\n[class*=\"  nav\"] ul,\nul[class*=\"  menu\"],\na[onclick][style*=\"  display\"],\na[id*=\"  ghosteryfirefox\"],\n#ghostery-purple-bubble,\n#translator-popup,\n.menu,\n.tooltip,\n.hovercard,\n.vbmenu_popup {\n    background-image: none !important;\n    background-color: transparent !important;\n    background: transparent !important;\n    /* background: rgba(5, 5, 5, 0) !important; */\n    /* border-radius: 5px; */\n    /* box-shadow: 1px 1px 5px #000 !important; */\n}\n\nheader,\n#header,\nfooter,\n#footer {\n    background: rgba(19, 19, 19, 0) !important;\n    box-shadow: 0 0 5px #000 !important;\n}\n\nbody>#dialog,\nbody>.xenOverlay {\n    /* color: #000 !important; */\n    background: rgba(19, 19, 19, 0) !important;\n    background-clip: padding-box !important;\n    box-shadow: 0 0 15px #000, inset 0 0 0 1px rgba(200, 200, 200, 0), inset 0 0 5px #111 !important;\n    border: 10px solid rgba(99, 99, 99, 0) !important;\n    border-radius: 0 !important;\n}\n\n[id*=\"  overlay\"],\n[id*=\"  lightbox\"],\nblockquote {\n    background-color: rgba(35, 35, 35, 0) !important;\n    border-radius: 5px\n}\n\npre,\ndl,\n.Message code {\n    background-color: rgba(5, 5, 5, 0) !important;\n}\n\n/*----- DEFAULT BUTTONS, SEARCHBOXES & CO -----*/\ninput,\nselect,\nbutton,\n[role=\"  button\"],\na.button,\na.submit,\na.BigButton,\na.TabLink,\n.install[onclick] {\n    -moz-appearance: none !important;\n    -webkit-appearance: none !important;\n    transition: border-color 0.3s !important;\n    /*  background: #060606 !important;                      \n                         text-shadow: 0 0 1px #008000 !important;                    \n                      */\n    background-color: transparent !important;\n    /* color: #000 !important; */\n\n    border: 2px solid #333 !important;\n    border-radius: 4px !important;\n    box-shadow: 0 0 2px rgba(0, 0, 0, 0.1) !important;\n}\n\na[href=\"  javascript:;\"],\na[class*=\"  button\"]:not(:empty),\na[id*=\"  button\"]:not(:empty),\na[id*=\"  Button\"]:not(:empty),\ndiv[class*=\"  button\"][onclick] {\n    transition: border-color 0.3s !important;\n    /*  background: #060606 !important;  */\n    background: transparent !important;\n    background-color: transparent !important;\n    /* color: #000 !important; */\n    text-shadow: 0 0 1px #FFD700 !important;\n    border-color: #333 !important;\n    box-shadow: 0 0 2px rgba(0, 0, 0, .1) !important;\n}\n\na[href=\"  javascript:;\"]:hover,\na[class*=\"  button\"]:not(:empty):hover,\na[id*=\"  button\"]:hover,\na[id*=\"  Button\"]:not(:empty):hover,\ndiv[class*=\"  button\"][onclick]:hover {\n    /*  background: #151515 !important; */\n    background: transparent !important;\n    color: #FFF !important;\n}\n\ninput *,\nselect *,\nbutton *,\na.button *,\na.submit * {\n    background-color: transparent !important;\n    color: #BBB !important;\n    text-shadow: none !important;\n}\n\ninput:hover,\ninput[type=\"  button\"]:hover,\nselect:hover,\nbutton:hover,\n[role=\"  button\"]:hover,\na.button:hover,\na.submit:hover,\na.BigButton:hover,\na.TabLink:hover {\n    background-color: transparent !important;\n    border: 2px solid #555 !important;\n    border-top-color: #555 !important;\n    border-bottom-color: #555 !important;\n    border-left-color: #555 !important;\n    border-right-color: #555 !important;\n}\n\ninput:focus,\nselect:focus {\n    background-color: transparent !important;\n    box-shadow: 0 0 5px #077 !important;\n}\n\ninput *:hover * {\n\n    color: #F0F0F0 !important;\n    text-shadow: 0 0 2px #FFF !important;\n}\n\ninput[disabled],\nselect[disabled],\nbutton[disabled],\ninput[disabled]:hover,\nselect[disabled]:hover,\nbutton[disabled]:hover,\ninput[disabled]:focus,\nselect[disabled]:focus,\nbutton[disabled]:focus {\n    opacity: 0.5 !important;\n    border-color: #333 !important;\n}\n\n/*                    \n             input[type=\"  checkbox\"  ], input[type=\"  radio\"  ] {                    \n                 box-shadow: 0 0 0 2px #444, 0 0 2px 2px #000 !important;                    \n                 opacity: 0.7;                    \n                 transition: box-shadow 0.2s, opacity 0.2s !important};                    \n             input[type=\"  checkbox\"  ]:not([disabled]):hover, input[type=\"  radio\"  ]:not([disabled]):hover {                    \n                 opacity: 0.9}                    \n             input[type=\"  checkbox\"  ]:not([disabled]):active, input[type=\"  radio\"  ]:not([disabled]):active {                    \n                 box-shadow: 0 0 0 2px #999, 0 0 2px 2px #000 !important};                    \n             input[type=\"  checkbox\"  ]:checked, input[type=\"  radio\"  ]:checked {                    \n                 box-shadow: 0 0 0 2px #077, 0 0 2px 2px #000 !important};                    \n             input[type=\"  checkbox\"  ][disabled], input[type=\"  radio\"  ][disabled] {                    \n                 opacity: 0.35}                    \n             */\ninput[type=\"  checkbox\"] {\n    background-color: transparent !important;\n    border-radius: 1px !important;\n}\n\ninput[type=\"  radio\"],\ninput[type=\"  radio\"]:focus {\n    background-color: transparent !important;\n    border-radius: 100% !important;\n}\n\ninput[type=\"  checkbox\"],\ninput[type=\"  radio\"] {\n    background-color: transparent !important;\n    min-width: 12px;\n    min-height: 12px;\n}\n\ninput[type=\"  checkbox\"]:checked,\ninput[type=\"  radio\"]:checked {\n    background-color: transparent !important;\n    border-color: #077 !important;\n    box-shadow: 0 0 5px #077 !important;\n}\n\nselect {\n    padding-right: 15px !important;\n    /*                    \n                 background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAcAAAAECAYAAABCxiV9AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAeSURBVBhXY5g5c+Z/BiwALo6uAEMDTACXSWgSDAwA4jATh950E30AAAAASUVORK5CYII=) no-repeat right 4px center #060606 !important;                    \n                 */\n    background-color: transparent !important;\n    transition: border-color 0.3s, background-position 0.3s !important;\n}\n\nbutton:active,\ninput[type=\"  submit\"]:active,\ninput[type=\"  button\"]:active,\na.button:active,\na[class*=\"  button\"]:not(:empty):active,\na.submit:active,\na.BigButton:active,\na.TabLink:active,\n.Active .TabLink {\n    /* *                    \n                 background: #292929 !important;                    \n                 background-image: -webkit-linear-gradient(left,rgb(0,0,0,0),rgb(0,0,0,0)) !important;                    \n                  background-image: linear-gradient(left,rgb(0,0,0,0),rgb(0,0,0,0)) !important;                    \n                  background-image: -webkit-gradient(left,rgb(0,0,0,0),rgb(0,0,0,0)) !important;                    \n                 */\n    background-image: none !important;\n    background-color: transparent !important;\n    background: transparent !important;\n    color: #FFF !important;\n}\n\ntextarea {\n    -moz-appearance: none !important;\n    -webkit-appearance: none !important;\n    background: rgba(0, 0, 0, 0) !important;\n    border-radius: 3px !important;\n    border: 1px solid #000 !important;\n    box-shadow: inset 0 0 8px #000 !important;\n    transition: border-color, background, 0.3s !important;\n}\n\ntextarea,\ntextarea * {\n    color: #C8C8C8 !important;\n    background-color: transparent !important;\n    text-shadow: 0 0 1px gray !important;\n}\n\ntextarea:hover,\ntextarea:focus:hover {\n    border-color: #333 !important;\n}\n\ntextarea:focus {\n    background: rgba(0, 0, 0, 0) !important;\n    border-color: #222 !important;\n}\n\ntextarea:focus,\ntextarea:focus>* {\n    background-color: transparent !important;\n    text-shadow: none !important;\n    box-shadow: none !important;\n}\n\noption,\noptgroup {\n    -moz-appearance: none !important;\n    -webkit-appearance: none !important;\n    background-color: transparent !important;\n    /* background: none !important; */\n    color: #666 !important;\n}\n\noptgroup {\n    /* background: #222 !important; */\n    background-color: transparent !important;\n    color: #DDD !important;\n}\n\noption:not([disabled]):hover,\noption:focus,\noption:checked {\n    /*	background: linear-gradient(#333, #292929) !important;  */\n    background-color: transparent !important;\n    color: #DDD !important;\n}\n\n/*----- IMAGE CHANGES -----*/\nbody,\n*:not(:empty):not(html):not(span):not(a):not(b):not(option):not(select):not(img):not([style=\"  display: block;\"]):not([onclick*=\"  open\"]):not([onclick*=\"  s_objectID\"]):not([class*=\"  stars\"]):not([id*=\"  stars\"]):not([id=\"  rating\"]):not([class=\"  rating\"]):not([class*=\"  SPRITE\"]):not([id*=\"  SPRITE\"]):not([class*=\"  item\"]):not([class*=cc-background]):not([id*=\"  item\"]):not([class*=\"  thumb\"]):not([class*=\"  icon\"]):not([class*=\"  photo\"]):not(.view):not(.text):not([id*=\"  lbImage\"]):not([class*=\"  cc-in\"]):not([class*=\"  gr-body\"]):not([id*=\"  watch\"]):not(#globalsearch),\n.r3_hm,\n.gmbutton2 b,\n.gtab-i,\n.ph,\n.bstab-iLft,\n.csb,\n#pagination div,\n[style*=\"  sprite2.png\"],\n#mw-head-base,\n#mw-page-base {\n    /* color: #000 !important; */\n    background-color: transparent !important;\n    background: transparent !important;\n    background-image: none !important;\n}\n\nimg {\n    background-color: transparent !important;\n    opacity: 1 !important;\n    /* transition: opacity .2s */\n}\n\nimg:hover,\na:hover img,\n#mpiv-popup {\n    opacity: 1 !important;\n}"



